### ISSUE TITLE
Curl::send() is deprecated

### ISSUE THREAD

**Issue by cseh-szabolcs** [kriswallsmith/Buzz#261]
Curl::send() is deprecated. Use Curl::sendRequest instead. But the Buzz\Browser-class still using the deprecated method.

**Comment by Nyholm** [comment]
Very true. There will be updates during next week. Those updates will break BC so I thought it was a good idea to add some deprecation notices before.

**Comment by stof** [comment]
@Nyholm the rule should generally be that your own non-deprecated code should not call your own deprecated code though (and CI can ensure that btw)

**Comment by stof** [comment]
@Nyholm the issue here is that all the existing high-level API of the Browser still relies on the Buzz Request and Response layer rather than on the PSR-7 layer (which is totally separate on the side). So the existing release is too early to deprecate the non-PSR-7 way IMO.

**Comment by Nyholm** [comment]
Yeah. In retrospect I agree with you. 

I suggest the next release should make sure that those high level functions uses the new code and returns PSR-7 response. What do you think about that?

**Comment by stof** [comment]
@Nyholm if you make a BC-breaking release changing all the return values for the high-level API, you should just drop the old Request/Response stuff at once in favor of PSR-7.

If you want a progressive way, a solution could be to make this in multiple steps:

- make `Browser::send` convert the Buzz request to PSR-7, then use the PSR-7 client API and convert back the response (similar to what https://github.com/symfony/psr-http-message-bridge does).
- apply middlewares in `Browser::send` in the PSR-7 layer
- convert all existing listeners to middlewares
- make a bridge allowing to wrap listeners into a middleware (so that they can move from the Buzz Message layer to the PSR-7 one), and deprecate registering listeners in favor of middlewares (the bridge middleware being the BC layer)
- convert the high-level APIs at this point only (which is the BC break) and drop the Buzz Message layer
