### ISSUE TITLE
Argument 2 passed to Buzz\Exception\NetworkException::__construct() must be of the type string, null given on OVH server (offre pro)

### ISSUE THREAD

**Issue by fonkyju** [kriswallsmith/Buzz#400]
Hi,

I have installed Mailgun-php and dependencies with 

`composer require mailgun/mailgun-php kriswallsmith/buzz nyholm/psr7`

Extract of my composer.json

```
	"require": {
		"php": ">=5.3.7",
		"swiftmailer/swiftmailer": "^5.4",
		"stripe/stripe-php": "^3.5",
		"mailgun/mailgun-php": "^2.8",
		"kriswallsmith/buzz": "^1.0",
		"nyholm/psr7": "^1.1"
	},
```

When I try to send a basic message like this 

```
$this->mg->messages()->send($this->apiDomain, [
        'from'    => 'web@'.$this->apiDomain,
        'to'      => 'julien.krier@gmail.com',
        'subject' => 'Voici un test de message',
        'text'    => 'As tu bien reçu ce message?'
      ]);
```

I have this error : 

An uncaught Exception was encountered

Type:        TypeError
Message:     Argument 2 passed to Buzz\Exception\NetworkException::__construct() must be of the type string, null given, called in /home/nomadou/www/vendor/kriswallsmith/buzz/lib/Client/FileGetContents.php on line 27
Filename:    /home/nomadou/www/vendor/kriswallsmith/buzz/lib/Exception/NetworkException.php
Line Number: 20

Backtrace:
	File: /home/nomadou/www/vendor/kriswallsmith/buzz/lib/Client/FileGetContents.php
	Line: 27
	Function: __construct

	File: /home/nomadou/www/vendor/php-http/client-common/src/HttpClientDecorator.php
	Line: 28
	Function: sendRequest

	File: /home/nomadou/www/vendor/php-http/client-common/src/PluginClient.php
	Line: 82
	Function: sendRequest

	File: /home/nomadou/www/vendor/php-http/client-common/src/Plugin/HistoryPlugin.php
	Line: 39
	Function: Http\Client\Common\{closure}

	File: /home/nomadou/www/vendor/php-http/client-common/src/PluginClient.php
	Line: 161
	Function: handleRequest

	File: /home/nomadou/www/vendor/php-http/client-common/src/Plugin/HeaderDefaultsPlugin.php
	Line: 41
	Function: Http\Client\Common\{closure}

	File: /home/nomadou/www/vendor/php-http/client-common/src/PluginClient.php
	Line: 161
	Function: handleRequest

	File: /home/nomadou/www/vendor/php-http/client-common/src/Plugin/AddHostPlugin.php
	Line: 64
	Function: Http\Client\Common\{closure}

	File: /home/nomadou/www/vendor/php-http/client-common/src/PluginClient.php
	Line: 161
	Function: handleRequest

	File: /home/nomadou/www/vendor/php-http/client-common/src/PluginClient.php
	Line: 175
	Function: Http\Client\Common\{closure}

	File: /home/nomadou/www/vendor/php-http/client-common/src/PluginClient.php
	Line: 88
	Function: Http\Client\Common\{closure}

	File: /home/nomadou/www/vendor/mailgun/mailgun-php/src/Mailgun/Api/HttpApi.php
	Line: 160
	Function: sendRequest

	File: /home/nomadou/www/vendor/mailgun/mailgun-php/src/Mailgun/Api/Message.php
	Line: 62
	Function: httpPostRaw

	File: /home/nomadou/www/application/frontend/libraries/Sendbymailgun.php
	Line: 50
	Function: send

	File: /home/nomadou/www/application/frontend/controllers/Cron.php
	Line: 27
	Function: mailGunTestMessage

	File: /home/nomadou/www/index.php
	Line: 321
	Function: require_once

 

In my local environment, I don't have problem to send this email. 

My problem is in a OVH server (mutualisé offre pro).

I don't know to make this works.

Any idea?

Thanks

**Comment by altcom-neil** [comment]
HI

I have just had this very problem on a local version of a site when it was working on a webserver.
The code is turning off all the errors before doing file_get_contents() and then turning them back on again after, hiding the true cause of the the erors I was actually having.

In lib/Client/FileGetContents.php lines 21-23
```
        $level = error_reporting(0);
        $content = file_get_contents($request->getUri()->__toString(), false, $context);
        error_reporting($level);
```

When I commented out the lines before and after file_get_contents() turning off error reporting I finally got the true cause of the errors:
`
Warning: failed loading cafile stream: 'C:/xampp-php72/tmp/cacert.pem' in Buzz\Client\FileGetContents->sendRequest()`

Which then cascaded down throught the SSL security making the file_get_contents request fail:
`
Warning: file_get_contents(): Failed to enable crypto in Buzz\Client\FileGetContents->sendRequest()`

I then added a pem file to my local systems tmp folder from https://curl.haxx.se/docs/caextract.html and now it all works again. I had in the distant past stuck a pem file in the tmp folder for some ssl testing and then forgotten about it, subsequently I had cleared out my tmp folder trying to free up space on the drive on my local machine assuming anything in tmp is temporary - silly me!

The actual error displayed is due to $error = error_get_last(); always seems to be returning 'null' if the file_get_contents() fails and returns false. I'm not sure if that is always the case or in some instances the function would return an error message but this is not checked for and so causes an Exception trying to create a NetworkException which seems a little ironic.

If you comment out the overriding of error reporting you may be able to determine better what is causing the problem for you.

I would think that this code should be updated to not turn off the error reporting and to check that error_get_last() returns something before trying to throw the new NetworkException and fall back to a simple NetworkException mesage if file_get_contents() fails to get any content - it may be that the other end simply timed out and these warnings should be in the log if error reporting hasn't been disabled.

```
        $content = file_get_contents($request->getUri()->__toString(), false, $context);
        if (false === $content) {
            if ( ($error = error_get_last()) ) {
              throw new NetworkException($request, $error['message']);
            }
            throw new NetworkException($request, 'Failed to get contents from '.$request->getUri()->__toString());
        }
```

Hope this helps you or anyone else running into this in the future!

Cheers, Neil

**Comment by dissolvdgrl** [comment]
Having the same problem now, works in local environment, but not on hosting (using shared hosting due to client restrictions sadly)

**Comment by Nyholm** [comment]
Try using the curl client if you have issues with your server's settings for `allow_url_fopen`,
